import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/components/",
        "/docs/",
        "/registry",
        "/themes",
        "/rtl",
        "/locales",
        "/mcp",
        "/pro",
        "/blocks",
        "/blocks/",
        "/templates",
        "/templates/",
        "/design-kit",
        "/pricing",
        "/license",
        "/commercial-license",
        "/refund",
        "/terms",
        "/privacy",
        "/support",
        "/contact",
        "/blog/",
        "/rss.xml",
        "/changelog.xml",
        "/llms.txt",
      ],
      disallow: [
        "/api/",
        "/auth/",
        "/sign-in",
        "/account",
        "/account/",
        "/checkout",
        "/checkout/",
        "/downloads/",
        "/components/lab$",
        "/preview/private/",
        "/templates/*/preview",
      ],
    },
    sitemap: "https://gummyui.dev/sitemap.xml",
    host: "https://gummyui.dev",
  };
}
